### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by annarusso** [annarusso/fld#1]
Write up a basic motivation of what we are interested in learning (and why!) intersected with what we might reasonably be able to ask

**Comment by ostriker** [comment]
Right now we are tending towards focusing on estimating how subsidized insurance has produced distortions in where people locate. Specifically, we want:
1) A literature/policy review section including things people have said about subsidized insurance distorting decisions, bonus points if there's no data to back them up
2) Description of first pass plan with 2017 Florida parcel data and FIRMs -- look at discontinuity across flood map lines, then control for elevation of ground. Next steps would be to move to discontinuities from outdated flood maps, which would take more time to find.
3) Description of ideal strategy - this would be a diff-in-diff combining the flood map zone discontinuity above and the 2012 policy change, so ideal data would have flood maps and parcel data from 2011 onwards.

**Comment by annarusso** [comment]
Hi Abby, 

I just revised the FLD-1 document reflecting some of what we talked about on Tuesday. It's still definitely rough (I'm planning to keep working on/thinking about/refining it), but I just wanted to ping you in case you wanted to take a look and / or had any major objections. A few of the cites I have saved on my Evernote just bc. it was annoying to PDF them, but I will PDF them eventually. Or could share you on the Evernote Notebook. 

Looking forward to hearing your thoughts (but enjoy this weekend of vacation... you are traveling correct??) 

Anna

**Comment by ostriker** [comment]
Thanks!! This looks great, I love the structure you've set up. My only 2 main thoughts are the following (also wrote in comments of word doc):
1. We should be specific about what we plan to put on the LHS. I think we discussed "assessed value per area" and "number of residential/commercial units" - does that sound right to you?
2. I'm not sure that the premium price rise in 2012 strictly holds information about risk constant, because premiums can signal risk. Even if the *actual* risk isn't changing, people's impressions of it may change. It seems to me like this is more disentangling the "map" channel of information from the "price" channel of information. Does that make sense? Let me know if I need to explain myself better...

Thanks!
Abby

**Comment by annarusso** [comment]
Hi Abby, 

Awesome!! Glad we are on the same page motivation-wise. Responding to your two comments: 
1. Specific about LHS variable: definitely!! I'm sure this will evolve over time / we will look at multiple things but I'm very happy with preliminary "main spec" being "assessed value per area" and "number of residential and/or commercial buildings." 

2. Premium price rise and information content: I totally see what you are saying, and I think a lot of the interpretation boils down to how we think people are interpreting different policy changes. The "map" channel has an obvious information signal -- you are in either in versus not in a "high risk" zone. The price change is trickier. While higher premiums on their own would signal risk, the 2012 change was in a way a "political" change, i.e. people's premia went up because they wanted to make the program more sustainable, but people's policies didn't increase differentially according to risk, making the policy change seem (at least to me) as a change unrelated to risk signals. BUT I definitely do think that in the case of the 2012 policy, price changes would signal risk if individuals were not really "paying attention" to the policy, and were just looking at their monthly bill, seeing that it increased, and thinking "this must mean that my expected probability of loss has increased." I think that we can discuss our estimates in the context of both the "map" versus "price" channel and the information versus premium channel and talk about the (serious!) limitations to interpreting our results as truly "information" versus "premium." Does that seem reasonable for now? 

One other thought is that we aren't really disentangling "map" channel versus "price" channel of information, as you write, because both the map and the price contain costs (which change people's behavior) plus information signals (which change people's behavior). So if we stick to strictly the map versus price difference, we would be disentangling the "map bundle" from the "premium change bundle." In this case, the premium difference between zone A and V is the same as the premium difference between 2011 and 2013, then any difference would be attributable to just map information, no? 

Maybe we should chat? I feel like I just rambled... 

Anna

**Comment by ostriker** [comment]
To recap what we just discussed offline, we are going to assume that the policy change does not change anyone's perception of *relative* risk, because it increased premiums across the board without regard to risk. (* Want to confirm that's true - I don't have as good a grasp on what the policy change consisted of as you do.) Therefore, the "map bundle" contains information about risk that the "premium change bundle" does not. 

I liked your framing of splitting decision-making into true risk, perceived risk, and financial costs. Under this framing, we are assuming that the "map bundle" affects (2) and (3) but the "premium change bundle" only affects (3).

Did I get this right?

**Comment by annarusso** [comment]
Yes, this sounds like what we discussed! Thanks for posting the recap :)
